### ISSUE TITLE
Adding a single SVG crashes Bridgetown.

### ISSUE THREAD

**Issue by wout** [andrewmcodes/bridgetown-inline-svg#3]
## What did you do?
Added the following svg tag:

```liquid
{% svg "/assets/svgs/default/logo.svg" %}
```

And tried a relative path as well:

```liquid
{% svg "assets/svgs/default/logo.svg" %}
```

Both with the same result.

## What did you expect to happen?
The icon to become embedded into my page.

## What actually happened?
Bridgetown crashes. If it's running, there is a single line of output:

```bash
Liquid Exception: undefined method `[]' for nil:NilClass in /home/wout/Code/Ruby/tilishop-website/src/_layouts/default.html
```

If the server is stopped and restarted again, the output is a bit more verbose:

```bash
[Bridgetown]   Liquid Exception: undefined method `[]' for nil:NilClass in /home/wout/Code/Ruby/tilishop-website/src/_layouts/default.html
[Bridgetown] bundler: failed to load command: bridgetown (/home/wout/.rbenv/versions/2.7.1/bin/bridgetown)
[Bridgetown] NoMethodError: undefined method `[]' for nil:NilClass
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/lib/bridgetown-core/liquid_extensions.rb:16:in `block in lookup_variable'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/lib/bridgetown-core/liquid_extensions.rb:15:in `each'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/lib/bridgetown-core/liquid_extensions.rb:15:in `lookup_variable'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-inline-svg-1.0.0/lib/bridgetown-inline-svg/svg-tag.rb:131:in `render'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-render-tag-0.2.0/lib/liquid-render-tag/tag.rb:61:in `render_to_output_buffer'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-render-tag-0.2.0/lib/liquid-render-tag/block_body.rb:179:in `block in render_node'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-render-tag-0.2.0/lib/liquid-render-tag/block_body.rb:189:in `disable_tags'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-render-tag-0.2.0/lib/liquid-render-tag/block_body.rb:178:in `render_node'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-render-tag-0.2.0/lib/liquid-render-tag/block_body.rb:160:in `render_to_output_buffer'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-render-tag-0.2.0/lib/liquid-render-tag/template.rb:225:in `block in render'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-render-tag-0.2.0/lib/liquid-render-tag/template.rb:262:in `with_profiling'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-render-tag-0.2.0/lib/liquid-render-tag/template.rb:224:in `render'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-render-tag-0.2.0/lib/liquid-render-tag/template.rb:240:in `render_to_output_buffer'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-render-tag-0.2.0/lib/liquid-render-tag/tags/render.rb:59:in `block in render_tag'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-render-tag-0.2.0/lib/liquid-render-tag/tags/render.rb:68:in `render_tag'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-render-tag-0.2.0/lib/liquid-render-tag/tags/render.rb:33:in `render_to_output_buffer'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-render-tag-0.2.0/lib/liquid-render-tag/block_body.rb:179:in `block in render_node'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-render-tag-0.2.0/lib/liquid-render-tag/registers/disabled_tags.rb:14:in `disable'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-render-tag-0.2.0/lib/liquid-render-tag/block_body.rb:190:in `disable_tags'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-render-tag-0.2.0/lib/liquid-render-tag/block_body.rb:178:in `render_node'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-render-tag-0.2.0/lib/liquid-render-tag/block_body.rb:160:in `render_to_output_buffer'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-render-tag-0.2.0/lib/liquid-render-tag/template.rb:225:in `block in render'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-render-tag-0.2.0/lib/liquid-render-tag/template.rb:262:in `with_profiling'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-render-tag-0.2.0/lib/liquid-render-tag/template.rb:224:in `render'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-render-tag-0.2.0/lib/liquid-render-tag/template.rb:236:in `render!'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/lib/bridgetown-core/liquid_renderer/file.rb:37:in `block (3 levels) in render!'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/lib/bridgetown-core/liquid_renderer/file.rb:51:in `measure_counts'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/lib/bridgetown-core/liquid_renderer/file.rb:36:in `block (2 levels) in render!'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/lib/bridgetown-core/liquid_renderer/file.rb:55:in `measure_bytes'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/lib/bridgetown-core/liquid_renderer/file.rb:35:in `block in render!'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/lib/bridgetown-core/liquid_renderer/file.rb:62:in `measure_time'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/lib/bridgetown-core/liquid_renderer/file.rb:34:in `render!'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/lib/bridgetown-core/renderer.rb:131:in `render_liquid'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/lib/bridgetown-core/renderer.rb:209:in `render_layout'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/lib/bridgetown-core/renderer.rb:178:in `place_in_layouts'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/lib/bridgetown-core/renderer.rb:91:in `render_document'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/lib/bridgetown-core/renderer.rb:66:in `run'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/lib/bridgetown-core/concerns/site/renderable.rb:46:in `render_regenerated'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/lib/bridgetown-core/concerns/site/renderable.rb:32:in `block (2 levels) in render_docs'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/lib/bridgetown-core/concerns/site/renderable.rb:31:in `each'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/lib/bridgetown-core/concerns/site/renderable.rb:31:in `block in render_docs'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/lib/bridgetown-core/concerns/site/renderable.rb:30:in `each_value'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/lib/bridgetown-core/concerns/site/renderable.rb:30:in `render_docs'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/lib/bridgetown-core/concerns/site/renderable.rb:15:in `render'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/lib/bridgetown-core/concerns/site/processable.rb:12:in `process'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/lib/bridgetown-core/commands/build.rb:71:in `build_site'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/lib/bridgetown-core/commands/build.rb:40:in `build'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/lib/bridgetown-core/commands/serve.rb:76:in `serve'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:40:in `block in register'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bridgetown-core-0.15.0/bin/bridgetown:22:in `<top (required)>'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/bin/bridgetown:23:in `load'
[Bridgetown]   /home/wout/.rbenv/versions/2.7.1/bin/bridgetown:23:in `<top (required)>'
error Command failed with exit code 1.
```
## Environment

**Ruby Version:** `ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]`

**Framework Version (Rails, whatever):** `bridgetown 0.15.0 "Overlook"`

**Dev Api Version:** `?`

**Comment by andrewmcodes** [comment]
@wout Do you have something like this in your Bridgetown config?

```
defaults:
  - scope:
      path: "assets/svgs"
    values:
      image: true
```

As well as a folder structure like `src` -> `assets` -> `svgs` -> `default` -> `logo.svg`

**Comment by wout** [comment]
@andrewmcodes I didn't have the `defaults` config, but it doesn't change anything after adding it (and restarting).

The folder structure is indeed the one you mention. I tried flattening the structure by putting everything in `src/assets/svgs`, but that doesn't solve the issue, either. The errors stay the same.

**Comment by andrewmcodes** [comment]
@wout any chance you can create a reproduction repo? I am using this on a fresh Bridgetown project as well with no issues. 

`undefined method '[]' ` is telling me that Bridgetown can't find the images you're trying to reference.

**Comment by andrewmcodes** [comment]
Also you might try running `bundle exec bridgetown clean` and then start Bridgetown again.

**Comment by andrewmcodes** [comment]
@wout I forgot about this before I was reminded. You need the `site` variable available to render the svg. My guess is you hit this error in a component or partial and this variable wasn't available. This is being changed in #4 so my guess is that once that is merged, you can update the gem in your project and it will work as expected.

**Comment by wout** [comment]
@andrewmcodes That could have been the case, yeah. I'm pretty happy with my current setup, though, as my plugin adds some additional features I need.

**Comment by andrewmcodes** [comment]
@wout awesome. I’m going to close this issue bc I believe the latest version removes the confusion that led to your error. Feel free to reopen if you end up trying it again and hit the same issue.
